# Generated by Django 5.1.1 on 2024-10-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='atrasada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='estado',
            field=models.CharField(max_length=200),
        ),
    ]
