# Generated by Django 5.1.1 on 2024-10-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_espaciodetrabajo_tablero_listatarea_tarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='listatarea',
            name='esta_llena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listatarea',
            name='max_wip',
            field=models.IntegerField(default=0),
        ),
    ]
