# Generated by Django 5.1.1 on 2024-10-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_listatarea_esta_llena_listatarea_max_wip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_tareas', models.IntegerField(default=0)),
                ('max_wip', models.IntegerField()),
                ('esta_llena', models.BooleanField(default=False)),
                ('posicion', models.IntegerField(default=0)),
                ('ultimo', models.BooleanField(default=True)),
                ('tablero_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_t', to='tasks.tablero')),
            ],
        ),
        migrations.AddField(
            model_name='tablero',
            name='listas',
            field=models.ManyToManyField(related_name='tablas', to='tasks.lista'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tasks.lista'),
        ),
        migrations.DeleteModel(
            name='ListaTarea',
        ),
    ]
