# Generated by Django 5.1.1 on 2024-11-10 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_user_tarea_usuario_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('imagen', models.ImageField(default='usuario_default.jpg', upload_to='perfiles/images/')),
                ('correo', models.CharField(max_length=200)),
                ('espacios', models.ManyToManyField(related_name='perfil_espacio', to='tasks.espaciodetrabajo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
