# Generated by Django 5.1.1 on 2024-10-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_lista_tablero_listas_alter_tarea_lista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='tablero_lista',
            new_name='tablero',
        ),
    ]
