# Generated by Django 5.1.1 on 2024-10-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_tablero_lista_lista_tablero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='posicion',
            field=models.IntegerField(default=1),
        ),
    ]
