# Generated by Django 5.1.1 on 2024-10-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_lista_posicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='lista',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lista',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lista',
            name='posicion2',
            field=models.IntegerField(default=1),
        ),
    ]
