# Generated by Django 5.1.1 on 2024-10-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_lista_options_lista_orden_lista_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='esta_llena',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='posicion',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='posicion2',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='ultimo',
        ),
    ]
